### ISSUE TITLE
Bogwitch Update

### ISSUE THREAD

**Issue by ddjammin** [remmizekim/ValheimMods#5]
This plugin now throws an error since the latest bogwitch update. Is this project still maintained. Wanted to see if there would be an update. 

[Info   :SaneInventory] SaneInventory - Patching in
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type Ship and name FixedUpdate and parameters
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static void SaneInventory.SaneInventory::ApplyShipWeightForce(Ship& __instance, UnityEngine.Rigidbody& ___m_body)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
SaneInventory.SaneInventory.Awake () (at <76dc5920d6964e5984561c9c07fc2cf3>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.GameObject:.cctor()
PlatformTools.Common.SingletonMonoBehaviour`1:get_Instance()
PlatformTools.PlatformManagerInitializer:OnRuntimeMethodLoad()

**Comment by remmizekim** [comment]
Sorry but I currently no longer maintaining this project.
